# Generated by Django 2.2 on 2019-05-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_nome', models.CharField(max_length=50, verbose_name='Nome Aluno')),
                ('aluno_ra', models.CharField(max_length=7, verbose_name='RA Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('etiqueta', models.SlugField(verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('etiqueta', models.SlugField(verbose_name='Etiqueta')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_nome', models.CharField(max_length=50, verbose_name='Nome Professor')),
                ('professor_re', models.CharField(max_length=7, verbose_name='Registro Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nome', models.CharField(max_length=50, verbose_name='Nome Usuario')),
                ('usu_senha', models.CharField(max_length=6, verbose_name='Senha Usuario')),
            ],
        ),
    ]
